name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev', 'master' (or 'main')
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: flutter test --coverage
        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          flags: smart-tests
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: vergissberlin/thinkport-thinkventory
          file: coverage/lcov.info
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2.2.3
        with:
          file: coverage/lcov.info
    
